### ISSUE TITLE
`@oneOf` directive support

### ISSUE THREAD

**Issue by leonardehrenfried** [magidoc-org/magidoc#319]
### Describe the problem

We would like to use `@oneOf` in our schema but magidoc fails to build the documentation with the following error:

```
Load GraphQL Schema [FAILED: Unable to extract a GraphQL introspection from provided schema: Error: Unknown directive "@oneOf".
```

### Describe the proposed solution

We would be ok if magidoc would simply ignore it. We can add support for it later.

### Importance

Would make my life easier

**Comment by pelletier197** [comment]
Seems like this is a built-in directive and GraphQL.js should support it out of the box. It should only be a matter of upgrading GraphQL.js and deploying a new version. I'll look into that.

**Comment by leonardehrenfried** [comment]
That would be fantastic!

**Comment by pelletier197** [comment]
I have just released 4.1.3. Let me know if this works for you now :slightly_smiling_face:. I have tried it on my side and it seemed to work fine.

**Comment by leonardehrenfried** [comment]
Thanks!

@optionsome can you try this?

**Comment by optionsome** [comment]
Thanks for the quick reply and reaction @pelletier197 . Unfornately, I tried with newer version now and the issue still persists. I can fix the issue by defining the directive in the schema file but with native GraphQL directives it shouldn't be necessary (although now quite sure what is the current status of this directive).

For context, our configuration of the introspection is as follow:
<details>
<pre>
introspection: {
    type: 'sdl',
    paths: ['src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls'],
  }
</pre>
</details>

**Comment by pelletier197** [comment]
Well I don't know why it worked earlier, must have made a mistake. But you're right, it doesn't work. This is a bit out of my control,  it seems like this is a quite recent addition to GraphQL-JS. It might not have been released yet. Last release seems to have been done in September. 

Would you mind posting the definition you used here for the directive for reference ? I'll make sure to update GraphQL library as soon as a new version is out

**Comment by optionsome** [comment]
Ok thank you for the information. The directive definition I used in the schema to get rid of the problem was:
```
"""
Exactly one of the fields on an input object must be set and non-null while all others are omitted.
"""
directive @oneOf on INPUT_OBJECT
```

**Comment by leonardehrenfried** [comment]
We had a very strange case of this problem re-appearing over the weekend. Suddenly our CI pipeline, which worked with @optionsome's manual addition for many weeks, stopped working, and superficially, nothing has changed.

I'm getting the following error:

```
vite v5.1.1 building SSR bundle for production...
transforming...
"GraphQLDirective", "GraphQLInterfaceType" and "GraphQLObjectType" are imported from external module "graphql" but never used in "src/lib/model.ts", "src/lib/components/tags/DirectiveTag.svelte", "src/lib/components/common/text/TypeLink.svelte", "src/lib/components/tags/TypeTag.svelte", "src/routes/types/[type]/+page.svelte" and "src/lib/components/tags/NullableTag.svelte".
✓ 2495 modules transformed.
rendering chunks...

node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
Error: Unknown directive "@oneOf".
    at assertValidSDL (/tmp/carbon-multi-page@4.1.4/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/tmp/carbon-multi-page@4.1.4/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at buildSchema (/tmp/carbon-multi-page@4.1.4/node_modules/graphql/utilities/buildASTSchema.js:109:10)
    at parseSchema (file:///tmp/carbon-multi-page@4.1.4/.svelte-kit/output/server/chunks/model.js:186:10)
    at file:///tmp/carbon-multi-page@4.1.4/.svelte-kit/output/server/chunks/model.js:28:16
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

Weirdly, If I change the spelling from `@oneOf` to `@oneof` then it works. Has anything changed recently that could be causing this?

**Comment by pelletier197** [comment]
GraphQL.js made an update a few days ago and they have implemented the `oneof` directive natively. https://github.com/graphql/graphql-js/releases/tag/v16.9.0

Unfortunately, the template ships without a lockfile, which might cause some libraries to update themselves. This is why it worked before and it stopped working. This usually doesn't cause problems.

Also, as of today, this feature is still not part of the official GraphQL specification, not even in the latest draft. Is using `@oneof` okay for you at this moment ? Otherwise we may raise the issue to GraphQL.js repository, but this bug is a little out of my control.

**Comment by leonardehrenfried** [comment]
I see. I'm going to have to check if graphql-java, which also reads in the schema file, still understands the validation rules when I change the spelling. I will come back to you on that one.

**Comment by pelletier197** [comment]
Alright. I will have a look about the possibility of shipping lockfiles with the template to avoid this behaviour.

**Comment by pelletier197** [comment]
For info, support for `@oneOf` has been added in the latest version. It will need to be added to the list of allowed directives for it to show up. 

If you added the `@oneOf` directive manully before, you may remove it now.

**Comment by pelletier197** [comment]
@leonardehrenfried let me know if you still experience issue with it.

**Comment by leonardehrenfried** [comment]
It works fantastically well, thank you!
